variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "cython python-pip python-numpy python-nose libtinyxml2-dev libboost-all-dev libjsoncpp-dev libgeos++-dev libgeos-dev qhull-bin libqhull-dev libltdl-dev libtasks-qld-dev libmc-rbdyn-urdf-dev python-tasks python-mc-rbdyn-urdf"
  GIT_DEPENDENCIES: "git@gite.lirmm.fr:multi-contact/eigen-lssol.git jrl-umi3218/Tasks"
  GITE_PACKAGES: "multi-contact/eigen-lssol multi-contact/tasks-packaging#topic/CIPackaging mc-hrp2/hrp2_drc mc-hrp4/hrp4#noxacro"
  MASTER_PPA: "v-launchpad-jochen-sprickerhof-de/pcl pierre-gergondet+ppa/multi-contact-unstable hrg/daily"
  ROS_DISTRO: "indigo"
  CMAKE_ADDITIONAL_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithDebInfo"

# Secured variable are stored in the project
# See: http://doc.gitlab.com/ci/variables/README.html

# Notifications (email/chatroom) are also handled by gitlab directly

# FIXME This version does not search for mc-env-description and hrp2_drc_description

before_script:
  - git submodule update --quiet --init --recursive
  - ./.jrl-ci/dependencies/eigen-3.2

build_debian:
  stage: build
  script:
    - export APT_DEPENDENCIES="cython python-pip python-numpy python-nose libtinyxml2-dev libboost-all-dev libjsoncpp-dev libgeos++-dev libgeos-dev qhull-bin libqhull-dev libltdl-dev"
    - export GIT_DEPENDENCIES="jrl-umi3218/Eigen3ToPython jrl-umi3218/SpaceVecAlg jrl-umi3218/eigen-qld git@gite.lirmm.fr:multi-contact/eigen-lssol.git jrl-umi3218/sch-core jrl-umi3218/sch-core-python jrl-umi3218/RBDyn jrl-umi3218/Tasks jrl-umi3218/mc_rbdyn_urdf"
    - export MASTER_PPA=""
    - export ROS_GIT_DEPENDENCIES="git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data git@gite.lirmm.fr:mc-hrp2/hrp2_drc#master git@gite.lirmm.fr:mc-hrp4/hrp4#master"
    - mkdir -p /tmp/_ci/catkin_dep_ws/src
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - debian

build_gcc_noros:
  stage: build
  script:
    - export ROS_DISTRO=""
    - ./.jrl-ci/run before_install
    - pushd .
    - cd /tmp && git clone --recursive git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data
    - cd /tmp && git clone -b master --recursive git@gite.lirmm.fr:mc-hrp2/hrp2_drc
    - cd /tmp && git clone -b master --recursive git@gite.lirmm.fr:mc-hrp4/hrp4
    - export CMAKE_ADDITIONAL_OPTIONS="-DHRP2_DRC_DESCRIPTION_PATH=/tmp/hrp2_drc/hrp2_drc_description -DHRP4_DESCRIPTION_PATH=/tmp/hrp4/hrp4_description -DMC_ENV_DESCRIPTION_PATH=/tmp/mc_rtc_ros_data/mc_env_description ${CMAKE_ADDITIONAL_OPTIONS}"
    - popd
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

build_gcc_ros:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/dependencies/catkin
    - export MASTER_PPA=""
    - export APT_DEPENDENCIES="ros-indigo-common-msgs ros-indigo-tf2-ros ros-indigo-xacro ros-indigo-rviz-animated-view-controller"
    - export GIT_DEPENDENCIES=""
    - export ROS_GIT_DEPENDENCIES="git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data git@gite.lirmm.fr:mc-hrp2/hrp2_drc#master git@gite.lirmm.fr:mc-hrp4/hrp4#master"
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

build_clang_ros:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/dependencies/catkin
    - export MASTER_PPA=""
    - export APT_DEPENDENCIES="ros-indigo-common-msgs ros-indigo-tf2-ros ros-indigo-xacro ros-indigo-rviz-animated-view-controller"
    - export GIT_DEPENDENCIES=""
    - export ROS_GIT_DEPENDENCIES="git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data git@gite.lirmm.fr:mc-hrp2/hrp2_drc#master git@gite.lirmm.fr:mc-hrp4/hrp4#master"
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - clang

build_with_script:
  stage: build
  script:
    - cd utils
    - ./build_and_install.sh
  tags:
    - GCC
  allow_failure: true

package_trusty_amd64_noros:
  stage: package
  before_script:
    - export ROS_DISTRO=""
    - export GITE_PACKAGES="$GITE_PACKAGES multi-contact/mc_rtc_ros_data@noros"
    - git submodule update --quiet --init --recursive
    - ./.packaging/setup_pbuilder.sh trusty amd64
    - sed -i -e"s@mc_rtc master@mc_rtc ${CI_BUILD_REF_NAME}@" .mc-rtc.recipe
  script:
    - ./.packaging/build_recipe.sh .mc-rtc.recipe trusty amd64
  artifacts:
    name: "mc_rtc_trusty_amd64"
    paths:
      - "*.deb"
    expire_in: '30d'
  tags:
    - GCC

package_trusty_amd64_ros:
  stage: package
  before_script:
    - export GITE_PACKAGES="$GITE_PACKAGES multi-contact/mc_rtc_ros_data@withros"
    - git submodule update --quiet --init --recursive
    - ./.packaging/setup_pbuilder.sh trusty amd64
    - sed -i -e"s@mc_rtc master@mc_rtc ${CI_BUILD_REF_NAME}@" .mc-rtc-ros.recipe
  script:
    - ./.packaging/build_recipe.sh .mc-rtc-ros.recipe trusty amd64
  artifacts:
    name: "mc_rtc_trusty_amd64"
    paths:
      - "*.deb"
    expire_in: '30d'
  tags:
    - GCC

package_trusty_i386_noros:
  stage: package
  before_script:
    - export ROS_DISTRO=""
    - export GITE_PACKAGES="$GITE_PACKAGES multi-contact/mc_rtc_ros_data@noros"
    - git submodule update --quiet --init --recursive
    - ./.packaging/setup_pbuilder.sh trusty i386
    - sed -i -e"s@mc_rtc master@mc_rtc ${CI_BUILD_REF_NAME}@" .mc-rtc.recipe
  script:
    - ./.packaging/build_recipe.sh .mc-rtc.recipe trusty i386
  artifacts:
    name: "mc_rtc_trusty_i386"
    paths:
      - "*.deb"
    expire_in: '30d'
  tags:
    - GCC

package_trusty_i386_ros:
  stage: package
  before_script:
    - export GITE_PACKAGES="$GITE_PACKAGES multi-contact/mc_rtc_ros_data@withros"
    - git submodule update --quiet --init --recursive
    - ./.packaging/setup_pbuilder.sh trusty i386
    - sed -i -e"s@mc_rtc master@mc_rtc ${CI_BUILD_REF_NAME}@" .mc-rtc-ros.recipe
  script:
    - ./.packaging/build_recipe.sh .mc-rtc-ros.recipe trusty i386
  artifacts:
    name: "mc_rtc_trusty_i386"
    paths:
      - "*.deb"
    expire_in: '30d'
  tags:
    - GCC

package_xenial_amd64_noros:
  stage: package
  before_script:
    - export ROS_DISTRO=""
    - export GITE_PACKAGES="$GITE_PACKAGES multi-contact/mc_rtc_ros_data@noros"
    - git submodule update --quiet --init --recursive
    - ./.packaging/setup_pbuilder.sh xenial amd64
    - sed -i -e"s@mc_rtc master@mc_rtc ${CI_BUILD_REF_NAME}@" .mc-rtc.recipe
  script:
    - ./.packaging/build_recipe.sh .mc-rtc.recipe xenial amd64
  artifacts:
    name: "mc_rtc_xenial_amd64"
    paths:
      - "*.deb"
    expire_in: '30d'
  tags:
    - GCC

package_xenial_amd64_ros:
  stage: package
  before_script:
    - export ROS_DISTRO="kinetic"
    - export GITE_PACKAGES="$GITE_PACKAGES multi-contact/mc_rtc_ros_data@withros"
    - git submodule update --quiet --init --recursive
    - ./.packaging/setup_pbuilder.sh xenial amd64
    - sed -i -e"s@mc_rtc master@mc_rtc ${CI_BUILD_REF_NAME}@" .mc-rtc-ros.recipe
  script:
    - ./.packaging/build_recipe.sh .mc-rtc-ros.recipe xenial amd64
  artifacts:
    name: "mc_rtc_xenial_amd64"
    paths:
      - "*.deb"
    expire_in: '30d'
  tags:
    - GCC

package_xenial_i386_noros:
  stage: package
  before_script:
    - export ROS_DISTRO=""
    - export GITE_PACKAGES="$GITE_PACKAGES multi-contact/mc_rtc_ros_data@noros"
    - git submodule update --quiet --init --recursive
    - ./.packaging/setup_pbuilder.sh xenial i386
    - sed -i -e"s@mc_rtc master@mc_rtc ${CI_BUILD_REF_NAME}@" .mc-rtc.recipe
  script:
    - ./.packaging/build_recipe.sh .mc-rtc.recipe xenial i386
  artifacts:
    name: "mc_rtc_xenial_i386"
    paths:
      - "*.deb"
    expire_in: '30d'
  tags:
    - GCC

package_xenial_i386_ros:
  stage: package
  before_script:
    - export ROS_DISTRO="kinetic"
    - export GITE_PACKAGES="$GITE_PACKAGES multi-contact/mc_rtc_ros_data@withros"
    - git submodule update --quiet --init --recursive
    - ./.packaging/setup_pbuilder.sh xenial i386
    - sed -i -e"s@mc_rtc master@mc_rtc ${CI_BUILD_REF_NAME}@" .mc-rtc-ros.recipe
  script:
    - ./.packaging/build_recipe.sh .mc-rtc-ros.recipe xenial i386
  artifacts:
    name: "mc_rtc_xenial_i386"
    paths:
      - "*.deb"
    expire_in: '30d'
  tags:
    - GCC

stages:
  - build
  - package
